### ISSUE TITLE
Parser expects there to be a components/messages property in the main schema

### ISSUE THREAD

**Issue by karlwbrown** [WaleedAshraf/asyncapi-validator#11]
The message validator loads the schema messages as follows:
    this._messages = this._schema.components.messages

However, the schema messages could be in another file, such as through a reference as follows:
```
channels:
  test:
    publish:
      message:
        oneOf:
          - $ref: './ref1.yml#components/messages/msg1'
          - $ref: './ref2.yml#components/messages/msg2'
```

Additionally, the logic assumes that all messages are in components/messages, which isn't always the case - the spec will allow messages to be placed directly under channels.

Could the parser be updated to actually parse the schema, and then walk down the tree accordingly?

**Comment by WaleedAshraf** [comment]
@karlwbrown 
About components/messages: That was fixed in a new release few weeks ago. Now, it also works if there are no components/messages. I have kept the old implementation also for backward compatibility.

Check this example: https://github.com/WaleedAshraf/asyncapi-validator#example-with-channel-validation

About other files, I have not tested that case. I think it should work as I parse (resolve all $refs) the schema first before doing the validation. And then use validate it like this.
```
payloadSchema = this._channels[channel][operation][key].payload
```

**Comment by karlwbrown** [comment]
Hi, I tried the example and it failed in the same way.

1) Example has `x-custome-key`: UserDeleted instead of `x-custom-key` (just a typo)
2) Once that is fixed I still get the same message using that example. I am using 2.4.1

```
(node:43185) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'messages' of undefined
    at new MessageValidator (/Users/kbrown/dev/va/pa-event-injector/node_modules/asyncapi-validator/src/MessageValidator.js:15:46)
    at ValidatorFactory.fromSource (/Users/kbrown/dev/va/pa-event-injector/node_modules/asyncapi-validator/src/ValidatorFactory.js:28:12)
    at async validateEvent (/Users/kbrown/dev/va/pa-event-injector/event-injector/src/test/js/validate-event.js:7:10)
(node:43185) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

**Comment by WaleedAshraf** [comment]
@karlwbrown thanks for pointing this out.
I have fixed the issue. Let me know if you are still facing any problem.
